### ISSUE TITLE
Model availability/status

### ISSUE THREAD

**Issue by saverkamp** [NYPL-discovery/discovery-models#10]
We need a property to designate availability or status of an item. What possible values will we need? Where does this come from in the record? Can this be a literal or do we need to model the value as an object?

Use bf:status if object
Mint local nypl:status if literal

cc @thisismattmiller @katesweeney @nonword

**Comment by thisismattmiller** [comment]
Possible Item statuses, these are from a table in sierra, but here is a list (along with recap partners, nypl in the middle)

https://docs.google.com/spreadsheets/d/1-dPBexFiHmJLAvHaWtLCHkGVbP5nom-zxFDPMaOKWe8/edit#gid=0

**Comment by saverkamp** [comment]
Do we need all the org-level status info, or is it enough to map all to the SCSB statuses to store in Discovery data: Available, Not Available, Loaned, InTransit, ShippedToILS, ShippedToReCAP

**Comment by saverkamp** [comment]
ex. 
<nypl:resource> nypl:status "Available" .

**Comment by thisismattmiller** [comment]
Probably want to keep it a code and apply that mapping in the application layer, if a new/existing code is changed or coopted for a new use would not want to have to reserialize everything. Or provided both, two predicates? code and "availability" both literals. I don't think there is any other data that needs it to be an object. From what I can think of.

**Comment by saverkamp** [comment]
Maybe add scheme, collection, or type to distinguish between orgs? How about something like this:
```
<http://data.nypl.org/statuses/1234> a nypl:Status ;
    skos:prefLabel "At bindery"
    skos:notation "i"
    skos:inScheme <http://data.nypl.org/statusSchemes/NYPL>
```

Or other thoughts on what's the best way to group these codes by org?

**Comment by katesweeney** [comment]
re: initial post, the STATUS(I) "item status" fixed-length field holds the item status/general availability code in Sierra item records. OPAC message and location code in item records also signify levels of availability (ex. opac messages about permission needed; location codes that signify both ownership and remote storage... these attributes generally aren't encoded in any other part of the record).

On some level we should also differentiate between available (place your hold), temporarily unavailable ("checked out" but you can join the hold queue) and definitely unavailable ("on display," "missing" or something that negates hold queueing). This might be useful for more than just RIH.

Has anyone documented which MARC fields and subfields NYPL uses for item record codes? Or can anyone on our team export full MARC records from Sierra? I was just denied permission for Sierra export functions (Data Exchange) but compromised for broad test server permissions

**Comment by saverkamp** [comment]
I also would like to know about documentation for NYPL's item record MARC field use. Maybe @jobinthomasnypl or @kfriedman can point us to the item record format that will be coming out of Kafka (or any documentation they have access to)?

**Comment by kfriedman** [comment]
@saverkamp, we're storing the item record directly as it comes from Sierra's API. You can see an example here: http://apidocs.nypltech.org/#!/items/getItems. Let me know if you have any other questions.

**Comment by saverkamp** [comment]
We will use bf:status and mint local nypl:Status objects using the sierra status codes. For mapping from ReCAP and partners, we will add two statuses: 
"r" : "Loaned (ReCAP)"
"na" : "Not available (ReCAP)"

Shawn will serialize.

**Comment by saverkamp** [comment]
Done. at https://github.com/NYPL-discovery/pcdm-store-updater/blob/master/data/statuses.json
