### ISSUE TITLE
Add property for item type and serialize

### ISSUE THREAD

**Issue by saverkamp** [NYPL-discovery/discovery-models#15]
We need a property for item type to represent sierra item type code. We will use a local predicate. Range will be an object with code and label. Codes will be at: https://drive.google.com/drive/u/1/folders/0B51-ZdfMu5sSbmRQbWNoejNxWUU. (@thisismattmiller will add)

**Comment by thisismattmiller** [comment]
Json added to the folder.

**Comment by saverkamp** [comment]
Postponing this to post-alpha. For alpha we are only using this to tell is an item is Research or Branch, and Paul is filtering out Branch pre-serialization.

**Comment by saverkamp** [comment]
We are adding this now. 

property: nypl:catalogItemType
range: nypl:CatalogItemType

Item type codes at: https://docs.google.com/spreadsheets/d/1YUZuG8yGS-7kW2uG2eU5K4YWThH-DN8_ucqJaDCAvw4/edit#gid=580006046
Map research item types only.

Serialization:
Use code for identifier.
```
<self> a nypl:CatalogItemType ;
    skos:notation "1" ;
    skos:prefLabel "non-circ" ;
    skos:note "General Materials" .
```

We will need to determine defaults or mapping for partner data. @katesweeney suggests the following: "you could map circulating/marli-able partner items to item type 55 ("book limited circ, MaRLI" as we do with our marli-able items); map in-library use partner items to item type 2 (book non-circ); map supervised use to item type 2 and supervised-use opac message (again like our items)."

TODO:
- serialize codes (@saverkamp)
- determine partner data mapping rules (@thisismattmiller, @katesweeney)
- add property and applicable data to item serialization (@nonword)

**Comment by saverkamp** [comment]
Serialized item types as CatalogItemType objects (added "catalog" for future semantic clarity when we bring other data sources into Discovery). json at: [pcdm-store-updater/data/sierra-codes-catalogItemTypes.json](https://github.com/NYPL-discovery/pcdm-store-updater/blob/master/data/sierra-codes-catalogItemTypes.json)

**Comment by nonword** [comment]
I've done this:

* add property and applicable data to item serialization (@nonword)
