### ISSUE TITLE
New title display field?

### ISSUE THREAD

**Issue by saverkamp** [NYPL-discovery/discovery-models#21]
Should we include a separate field for display title? We mapped the whole 245 field for alpha which included the statement of responsibility, something we wouldn't include in a title field. This made it easy to provide a nice display in search results (rather than writing rules to construct a display title out of title + creator/contributor), and we preserve keyword searchability of statement of responsibility (which can differ from authorized name) but it means we will need to generate similar display titles for non-MARC sources.

Option 1:
2 fields: title (with just 245 $a $b) and displayTitle with the entire 245. For any new non-MARC data we will have to construct a displayTitle consistent with MARC 245 syntax

Option 2:
1 title field with just the 245 $a $b. We generate display title on the fly by concatenating title + contributor literal. 

cc @thisismattmiller @beefoo @nonword

**Comment by thisismattmiller** [comment]
This also gets into sort title, there is a field in sierra that indicates what offset the real title starts at:
```
{
  "title": "The big, bad book of botany [electronic resource] : the world's most fascinating flora",
   ...
  "fixedFields": {
   ....
    "25": {
      "label": "Skip",
      "value": "4"
    }
  ...
  }
   ...
}
```
This will only be in Sierra records though. I don't know if elastic can do that already? Like filter out stop words?

I personally think option 1 is better and index both fields to allow searching statement of responsibility.

**Comment by saverkamp** [comment]
I also like option 1.

I would like to avoid mapping over the nonfiling character data if at all possible. We won't have this for most non-MARC data sources. I would imagine elasticsearch should have a way to filter out stopwords before sort. @nonword do you know?

**Comment by saverkamp** [comment]
Unless anyone has strong opinions, let's go with option 1 to add a property for display title and leave out the nonfiling characters. I've updated the properties and mapping documents. New property is called 'Title display' (nypl:titleDisplay). 

-- need to update serializer code and display (@nonword and @beefoo , let me know if you want me to break this out into a new issue)
