### ISSUE TITLE
Re-map call number

### ISSUE THREAD

**Issue by saverkamp** [NYPL-discovery/discovery-models#23]
Call number (nypl:shelfmark) is currently mapped from a sierra convenience field, but much of this data includes the subfield label. We should instead map this from the 852 $h field for NYPL and all partner data. 

Updated documentation at https://docs.google.com/spreadsheets/d/1RtDxIpzcCrVqJqUjmMGkn8n2hX3BZVN9QvbB1HRgx1c/edit#gid=0

**Comment by thisismattmiller** [comment]
It should probably go convenience field first, then 852, sometimes it is not in 852 but somehow made it into the convenience field.

**Comment by thisismattmiller** [comment]
Just strip out |h from the convenience field.
