### ISSUE TITLE
Map OPAC message (as Access message) and serialize codes

### ISSUE THREAD

**Issue by saverkamp** [NYPL-discovery/discovery-models#33]
We will need the Sierra code "OPAC message" to determine and display allowed uses of materials. This will also be used to calculate the boolean "Requestable" field, used to determine if an item can be requested for hold. 

NYPL property: nypl:accessMessage
range: nypl:AccessMessage

OPAC message codes at: https://docs.google.com/spreadsheets/d/1YUZuG8yGS-7kW2uG2eU5K4YWThH-DN8_ucqJaDCAvw4/edit#gid=1957101857
Map only those that apply to research items (Note field: "Research only" or applicable blank fields)

Serialization:
Use code for identifier.
```
<self>  a nypl:AccessMessage ;
    skos:notation "1" ;
    skos:preflabel "USE IN LIBRARY" .
```

We will need to determine defaults or mapping rules for partner data.

TODO:
- ~~serialize codes (@saverkamp)~~
- determine partner data mapping rules (@thisismattmiller, @katesweeney)
- add property and applicable data to item serialization (@nonword)

**Comment by saverkamp** [comment]
Serialized codes as AccessMessage objects at [pcdm-store-updater/data/sierra-codes-accessMessages.json](https://github.com/NYPL-discovery/pcdm-store-updater/blob/master/data/sierra-codes-accessMessages.json)

**Comment by nonword** [comment]
I've done this part:

* add property and applicable data to item serialization (@nonword)
