### ISSUE TITLE
Update call number (nypl:shelfMark) mapping to accommodate serial volumes

### ISSUE THREAD

**Issue by saverkamp** [NYPL-discovery/discovery-models#43]
Join 852$h and field tag 'v' value with a space.
Example: i11937947
852$h: L-11 3247
fieldTag v: 1971-72
nypl:shelfMark : L-11 3247 1971-72

TODO
- ~~update mapping document (@saverkamp)~~
- update serializer code (@nonword)

**Comment by nonword** [comment]
serializer implements this now (has for some time, but perhaps some items need to be reserialized)

https://github.com/NYPL-discovery/pcdm-store-updater/blob/master/lib/serializers/item.js#L137

**Comment by nonword** [comment]
Confirmed serializing - e.g. https://api.nypltech.org/api/v0.1/discovery/resources/b10283722
