### ISSUE TITLE
Partial LCC?

### ISSUE THREAD

**Issue by seanredmond** [NYPL-discovery/discovery-models#48]
https://catalog.nypl.org/record=b10058563~S1
http://dev-discovery.nypl.org/bib/b10058563

in MARC: `908  0 PA6519|b.M9L4`

in API: `"idLcc":["PA6519"]`

**Comment by saverkamp** [comment]
Hi Sean, 
What is the issue?

**Comment by seanredmond** [comment]
The LCC should be PA6519.M9L4, but only the "PA6519" part is showing up in the API

**Comment by saverkamp** [comment]
Just the first part of that number is the classification (PA6519). The second part is the item number. Together they make up LC call number. See https://www.loc.gov/marc/bibliographic/bd050.html for more info on LC numbers (specifically under "Subfield Codes" $a and $b).

If the full LC call number is being requested, let me know and I'll change the mapping. But the mapping for LC classification is correct.

**Comment by seanredmond** [comment]
Yes. It would be useful for the front end to have the LC call number.

**Comment by saverkamp** [comment]
Is that what Denise is asking for?

**Comment by seanredmond** [comment]
I can double check with her

**Comment by seanredmond** [comment]
According to Denise classification is fine.
